create table if not exists groups
(
    id         bigint generated by default as identity constraint groups_pkey primary key,
    created_at date,
    title      varchar(255)
);

create table if not exists notes
(
    id         bigint generated by default as identity constraint notes_pkey primary key,
    body       varchar(2048),
    created_at timestamp,
    title      varchar(255),
    group_id   bigint  constraint notes_groups_id references groups
);

